@startuml Channel Protocol

skinparam participantStyle rectangle
skinparam defaultFontSize 24

skinparam horizontalPadding  4
skinparam verticalPadding    2



participant "Service A (VM1)" as Client <<Client>>
participant "Hypervisor" as Host <<Trusted Host>>
participant "Service B (VM2)" as Server <<Server>>


== Client Hello ==
Client -> Host : Client Hello\n(Metadata with ClientRandom)

== Trusted Host (Hypervisor) Hello ==
Host -> Client : Trusted Host Hello\n(Certificate with metadata)
note over Client,Host: Temporary channel established

== Client Authentication and Challenge ==
Client -> Host : Client Authentication & Challenge\n(Client certificate with signature,\n target service ID)

== Host Verification and Server Request ==
Host -> Host : Validate client's certificate and challenge
note over Host,Server: Temporary channel established
Host -> Server : Forward connection request

== Server Hello ==
Server -> Host : Server Hello\n(Server certificate, cryptographic challenge,\ncipher suites, acceptance of request)

== Trusted Host Authorization and Channel Creation ==
Host -> Host : Validate server's certificate and challenge
note over Client,Server: Secure channel(between Server and Client) is created
note over Client,Server: Temporary channels are deleted
Host -> Client : Notify: Secure IVSHMEM channel created

' == Session Key Negotiation (Optional, Only for higher security) ==
' Client -> Server : Exchange shared secret
' Server -> Client : Acknowledge key exchange

== Secure Data Transfer ==
Client <-> Server : Secure data transfer


@enduml
